#!/usr/bin/env python3
"""Generate character voices for every line in src/script.ts.

Uses Kokoro-82M (Apache-2.0 open-weights TTS) via the `kokoro-onnx` package.
    pip install kokoro-onnx soundfile
The model (~330 MB) is downloaded to tools/.models/ on first run.

Outputs:
  public/audio/voice/<line-id>.mp3   (or .wav if ffmpeg is missing)
  src/generated/voiceManifest.ts     (durations + the text each file was made from)

Only lines whose text changed (or whose file is missing) are regenerated.
"""
import json
import os
import shutil
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(ROOT, "tools", ".models")
VOICE_DIR = os.path.join(ROOT, "public", "audio", "voice")
MANIFEST_TS = os.path.join(ROOT, "src", "generated", "voiceManifest.ts")
MODEL_URL = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/"

# Two clearly different voices: bright young US voice vs. older British voice.
VOICES = {
    "hikari": {"voice": "af_bella", "speed": 1.1, "lang": "en-us"},
    "professor": {"voice": "bm_george", "speed": 1.08, "lang": "en-gb"},
}


def ensure_model():
    os.makedirs(MODEL_DIR, exist_ok=True)
    paths = {}
    for local, remote in [("kokoro.onnx", "kokoro-v1.0.onnx"), ("voices.bin", "voices-v1.0.bin")]:
        p = os.path.join(MODEL_DIR, local)
        if not os.path.exists(p):
            print(f"Downloading {remote} ...", flush=True)
            urllib.request.urlretrieve(MODEL_URL + remote, p)
        paths[local] = p
    return paths


def load_lines():
    out = subprocess.check_output(["npx", "tsx", "tools/export-lines.ts"], cwd=ROOT)
    return json.loads(out)


def load_existing_manifest():
    if not os.path.exists(MANIFEST_TS):
        return {}
    src = open(MANIFEST_TS, encoding="utf-8").read()
    start = src.find("= ") + 2
    end = src.rfind(";")
    try:
        return json.loads(src[start:end])
    except Exception:
        return {}


def main():
    import numpy as np
    import soundfile as sf
    from kokoro_onnx import Kokoro

    lines = load_lines()
    manifest = load_existing_manifest()
    paths = ensure_model()
    kokoro = Kokoro(paths["kokoro.onnx"], paths["voices.bin"])
    os.makedirs(VOICE_DIR, exist_ok=True)
    use_mp3 = shutil.which("ffmpeg") is not None
    force = "--force" in sys.argv

    new_manifest = {}
    for line in lines:
        cfg = VOICES[line["speaker"]]
        ext = "mp3" if use_mp3 else "wav"
        fname = f"{line['id']}.{ext}"
        fpath = os.path.join(VOICE_DIR, fname)
        old = manifest.get(line["id"])
        if (not force and old and old.get("tts") == line["tts"] and old.get("voice") == cfg["voice"]
                and os.path.exists(os.path.join(VOICE_DIR, old["file"]))):
            new_manifest[line["id"]] = old
            continue
        samples, sr = kokoro.create(line["tts"], voice=cfg["voice"], speed=cfg["speed"], lang=cfg["lang"])
        # Trim leading/trailing near-silence so timing is tight.
        idx = np.where(np.abs(samples) > 0.01)[0]
        if len(idx):
            pad = int(0.05 * sr)
            samples = samples[max(0, idx[0] - pad): min(len(samples), idx[-1] + pad)]
        wav_path = os.path.join(VOICE_DIR, f"{line['id']}.wav")
        sf.write(wav_path, samples, sr)
        if use_mp3:
            subprocess.check_call(["ffmpeg", "-y", "-loglevel", "error", "-i", wav_path,
                                   "-codec:a", "libmp3lame", "-q:a", "3", fpath])
            os.remove(wav_path)
        seconds = round(len(samples) / sr, 3)
        new_manifest[line["id"]] = {"file": fname, "seconds": seconds, "tts": line["tts"], "voice": cfg["voice"]}
        print(f"  {line['id']:<10} {seconds:5.2f}s  {line['tts']}", flush=True)

    # Remove audio for lines that no longer exist.
    keep = {v["file"] for v in new_manifest.values()}
    for f in os.listdir(VOICE_DIR):
        if f not in keep and f.endswith((".mp3", ".wav")):
            os.remove(os.path.join(VOICE_DIR, f))

    with open(MANIFEST_TS, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by tools/generate_tts.py. Do not edit by hand.\n")
        fh.write("export interface VoiceClip {file: string; seconds: number; tts: string; voice: string}\n")
        fh.write("export const VOICE_MANIFEST: Record<string, VoiceClip> = ")
        fh.write(json.dumps(new_manifest, indent=2, ensure_ascii=False))
        fh.write(";\n")
    total = sum(v["seconds"] for v in new_manifest.values())
    print(f"Done. {len(new_manifest)} clips, {total:.1f}s of dialogue.")


if __name__ == "__main__":
    main()
